{% set name = "coser" %}
{% set version = "0.1.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source: https://github.com/LiuShang-777/coser/archive/refs/tags/v0.1.0.tar.gz
  sha256: 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  entry_points:
    - coser = coser.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - numpy
    - pandas
    - scipy
    - scikit-learn

test:
  requires:
    - python {{ python_min }}
  imports:
    - coser
  commands:
    - coser --help

about:
  home: https://github.com/LiuShang-777/coser_for_conda
  license: MIT
  license_file: LICENSE
  summary: CoSEr coupling score calculator for paired traits.

extra:
  recipe-maintainers:
    - YOUR_GITHUB_USERNAME
